### ISSUE TITLE
nits

### ISSUE THREAD

**Issue by pinheadmz** [chaincodelabs/lightning-scavenger-hunt#1]
the invoice generator invoices expire in 24h, students prob need more time than that :-)

```
2024-01-18 20:09:03.551 [DBG] INVC: 
 Invoice(pay_hash=ae9dddb405be7da3d12db73e9818d737cb67fc7f0b8db167e9f67123642387f6): 
 added with terms amt=5550000 mSAT, expiry=24h0m0s, final_cltv_delta=80
```

also I think the markdown link is wrong in the `Setup Lightning Invoices` section

**Comment by pinheadmz** [comment]
Also, shouldn't the the script output the preimages? I think its printing the hashes currently

**Comment by carlaKC** [comment]
> Also, shouldn't the the script output the preimages? I think its printing the hashes currently

We hash the student provided preimage in the check then look it up.

**Comment by carlaKC** [comment]
> the invoice generator invoices expire in 24h 

👍 updated to 2 weeks

**Comment by carlaKC** [comment]
> also I think the markdown link is wrong in the Setup Lightning Invoices section

I think I fixed this since this was opened, be reopen if something is still off!
